
[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm start"

[[edge_functions]]
  path = "/access/*"
  function = "login"

[[edge_functions]]
  path = "/signout"
  function = "signout"

[[edge_functions]]
  path = "/*"
  function = "eleventy-edge"
